stages:
  - lint
  - build

# pre-commit:
#   stage: lint
#   image: python:latest
#   before_script:
#     - pip install pre-commit
#     - pre-commit install
#   script:
#     - pre-commit run --all-files

docker:
  stage: build
  script:
    - docker build --tag server -f Dockerfile .
    - docker build --tag emulator -f Dockerfile .
  only:
    - master
