version: "3"
services:
  server:
    build:
      context: .
      target: server
    ports:
      - 6789:6789
    depends_on:
      - "redis"
  emulator:
    build:
      context: .
      target: emulator
    depends_on:
      - "rtmp"
      - "redis"
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  rtmp:
    image: "tiangolo/nginx-rtmp"
    ports:
      - 1935:1935

# build mgba dans le conteuneur car broken path sinon
