version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - WEBSOCKET_SERVE=$WEBSOCKET_SERVE
      - WEBSOCKET_PORT=$WEBSOCKET_PORT
    ports:
      - $WEBSOCKET_PORT:$WEBSOCKET_PORT
    depends_on:
      - redis
    restart: unless-stopped

  emulator:
    build:
      context: .
      dockerfile: Dockerfile
      target: emulator
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - RTMP_HOST=$RTMP_HOST
      - RTMP_PORT=$RTMP_PORT
      - EMULATOR_RAND_RATE=0.2
    depends_on:
      - rtmp
      - redis
    volumes:
      - ./states/:/code/states/
      - ./roms/:/code/roms/
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - $REDIS_PORT:6379
    restart: unless-stopped

  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - $RTMP_PORT:1935
    restart: unless-stopped
