version: "3"
services:
  server:
    build:
      context: .
    entrypoint: poetry run python src/server.py
    ports:
      - 6789:6789
    depends_on:
      - "redis"
  emulator:
    build:
      context: .
    entrypoint: poetry run python src/emulator.py
    depends_on:
      - "rtmp"
      - "redis"
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  rtmp:
    image: "tiangolo/nginx-rtmp"
    ports:
      - 1935:1935
